// ─── Imports ────────────────────────────────────────────────────────────────

import type { Metadata } from 'next'
import { openSans } from '@/lib/fonts'

import '@/styles/globals.css'
import { MainLayout } from '@/components/shared'

// ─── Metadados da Aplicação ─────────────────────────────────────────────────

export const metadata: Metadata = {
  title: 'QuickShop',
  description: 'Generated by create next app',
}

// ─── Componente RootLayout ──────────────────────────────────────────────────

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${openSans.variable} font-sans antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
