import type { Metadata } from 'next'
import { openSans } from '@/lib/fonts'

import '@/styles/globals.css'
import MainLayout from '@/components/shared/MainLayout'

export const metadata: Metadata = {
  title: 'QuickShop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${openSans.variable} font-sans antialiased bg-white text-zinc-900`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
